import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

import '../../features/auth/domain/player.dart';

/// PDF Export Service for player performance reports
class PdfExportService {
  static final PdfExportService instance = PdfExportService._();
  PdfExportService._();

  /// Generate player profile PDF
  Future<Uint8List> generatePlayerProfilePdf({
    required Player player,
    required Map<String, dynamic> stats,
    required List<Map<String, dynamic>> tournaments,
    required List<Map<String, dynamic>> handicapHistory,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('MMMM d, yyyy');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          _buildHeader(player, dateFormat),
          pw.SizedBox(height: 20),

          // Summary Stats
          _buildSummarySection(stats),
          pw.SizedBox(height: 20),

          // Handicap History
          if (handicapHistory.isNotEmpty) ...[
            _buildSectionTitle('Handicap History'),
            _buildHandicapChart(handicapHistory),
            pw.SizedBox(height: 20),
          ],

          // Tournament Results
          if (tournaments.isNotEmpty) ...[
            _buildSectionTitle('Recent Tournament Results'),
            _buildTournamentTable(tournaments),
            pw.SizedBox(height: 20),
          ],

          // Performance Stats
          _buildSectionTitle('Performance Statistics'),
          _buildPerformanceStats(stats),
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Generated by D1 Golf Tracker • ${dateFormat.format(DateTime.now())}',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
            ),
          ),
        ),
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(Player player, DateFormat dateFormat) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.green800,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                player.fullName,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.white,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Phase ${player.currentPhase} • ${player.gaNumber ?? ""}',
                style: const pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.white,
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                'GA Handicap',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey300,
                ),
              ),
              pw.Text(
                '${player.currentHandicap?.toStringAsFixed(1) ?? "N/A"}',
                style: pw.TextStyle(
                  fontSize: 28,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.white,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSectionTitle(String title) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 16,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.green800,
        ),
      ),
    );
  }

  pw.Widget _buildSummarySection(Map<String, dynamic> stats) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _buildStatItem(
            'Tournaments',
            '${stats['totalTournaments'] ?? 0}',
          ),
          _buildStatItem(
            'Avg Score',
            '${(stats['averageScore'] as double?)?.toStringAsFixed(1) ?? "N/A"}',
          ),
          _buildStatItem(
            'Best Finish',
            '${stats['bestFinish'] ?? "N/A"}',
          ),
          _buildStatItem(
            'Win Rate',
            '${((stats['winRate'] as double?) ?? 0 * 100).toStringAsFixed(1)}%',
          ),
        ],
      ),
    );
  }

  pw.Widget _buildStatItem(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(
            fontSize: 10,
            color: PdfColors.grey600,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 18,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    );
  }

  pw.Widget _buildHandicapChart(List<Map<String, dynamic>> history) {
    // Simple text-based representation since pdf charts are complex
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          for (final entry in history.take(10))
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 2),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    entry['date']?.toString() ?? '',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                  pw.Text(
                    '${(entry['value'] as num?)?.toStringAsFixed(1) ?? ""}',
                    style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  pw.Widget _buildTournamentTable(List<Map<String, dynamic>> tournaments) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      columnWidths: {
        0: const pw.FlexColumnWidth(2),
        1: const pw.FlexColumnWidth(1),
        2: const pw.FlexColumnWidth(1),
        3: const pw.FlexColumnWidth(1),
        4: const pw.FlexColumnWidth(1),
      },
      children: [
        // Header row
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey200),
          children: [
            _buildTableCell('Tournament', isHeader: true),
            _buildTableCell('Date', isHeader: true),
            _buildTableCell('Score', isHeader: true),
            _buildTableCell('Position', isHeader: true),
            _buildTableCell('Field', isHeader: true),
          ],
        ),
        // Data rows
        ...tournaments.take(10).map((t) => pw.TableRow(
              children: [
                _buildTableCell(t['name']?.toString() ?? ''),
                _buildTableCell(t['date']?.toString() ?? ''),
                _buildTableCell('${t['score'] ?? ""}'),
                _buildTableCell('${t['position'] ?? ""}'),
                _buildTableCell('${t['fieldSize'] ?? ""}'),
              ],
            )),
      ],
    );
  }

  pw.Widget _buildTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  pw.Widget _buildPerformanceStats(Map<String, dynamic> stats) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Column(
        children: [
          _buildStatRow('Fairways in Regulation (FIR)',
              '${(stats['fir'] as double?)?.toStringAsFixed(1) ?? "N/A"}%'),
          _buildStatRow('Greens in Regulation (GIR)',
              '${(stats['gir'] as double?)?.toStringAsFixed(1) ?? "N/A"}%'),
          _buildStatRow('Putts per Round',
              '${(stats['puttsPerRound'] as double?)?.toStringAsFixed(1) ?? "N/A"}'),
          _buildStatRow('Up & Down %',
              '${(stats['upAndDown'] as double?)?.toStringAsFixed(1) ?? "N/A"}%'),
          _buildStatRow('Sand Save %',
              '${(stats['sandSave'] as double?)?.toStringAsFixed(1) ?? "N/A"}%'),
        ],
      ),
    );
  }

  pw.Widget _buildStatRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10)),
          pw.Text(
            value,
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  /// Preview and print PDF
  Future<void> previewPdf(Uint8List pdfBytes, String title) async {
    await Printing.layoutPdf(
      onLayout: (format) => pdfBytes,
      name: title,
    );
  }

  /// Share PDF
  Future<void> sharePdf(Uint8List pdfBytes, String filename) async {
    await Printing.sharePdf(bytes: pdfBytes, filename: filename);
  }

  /// Generate tournament report PDF
  Future<Uint8List> generateTournamentReportPdf({
    required Map<String, dynamic> tournament,
    required List<Map<String, dynamic>> rounds,
    required List<Map<String, dynamic>> holeScores,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // Tournament header
            pw.Text(
              tournament['name']?.toString() ?? 'Tournament Report',
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              '${tournament['date'] ?? ""} • ${tournament['course'] ?? ""}',
              style: const pw.TextStyle(
                fontSize: 12,
                color: PdfColors.grey600,
              ),
            ),
            pw.SizedBox(height: 20),

            // Results summary
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                color: PdfColors.green50,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                children: [
                  _buildStatItem('Total Score',
                      '${tournament['totalScore'] ?? ""}'),
                  _buildStatItem(
                      'vs Par', '${tournament['scoreToPar'] ?? ""}'),
                  _buildStatItem(
                      'Position', '${tournament['position'] ?? ""}'),
                  _buildStatItem(
                      'Field Size', '${tournament['fieldSize'] ?? ""}'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Rounds summary
            if (rounds.isNotEmpty) ...[
              pw.Text(
                'Round Scores',
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                    children: [
                      _buildTableCell('Round', isHeader: true),
                      _buildTableCell('Course', isHeader: true),
                      _buildTableCell('Score', isHeader: true),
                      _buildTableCell('Putts', isHeader: true),
                      _buildTableCell('FIR%', isHeader: true),
                      _buildTableCell('GIR%', isHeader: true),
                    ],
                  ),
                  ...rounds.map((r) => pw.TableRow(
                        children: [
                          _buildTableCell('R${r['roundNumber']}'),
                          _buildTableCell(r['course']?.toString() ?? ''),
                          _buildTableCell('${r['score'] ?? ""}'),
                          _buildTableCell('${r['putts'] ?? ""}'),
                          _buildTableCell(
                              '${(r['fir'] as double?)?.toStringAsFixed(0) ?? ""}%'),
                          _buildTableCell(
                              '${(r['gir'] as double?)?.toStringAsFixed(0) ?? ""}%'),
                        ],
                      )),
                ],
              ),
            ],
          ],
        ),
      ),
    );

    return pdf.save();
  }
}
